<html>
	<head>
		<meta charset="utf-8">
		<title>A sample PHP page</title>
	</head>
	<body>
		<h1> HTML and PHP sample page</h1>
		<div>
<?php
	print "<p>A message generated by PHP.</p>";
?>
		</div>
		<div>
			<h2>Some more HTML</h2>
		</div>
		<div>
			<p>A mix of HTML <?php print "and PHP together"; ?></p>
		</div>

	</body>
</html>
